/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CloudRouteImport } from './routes/_cloud'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CloudPumpRouteImport } from './routes/_cloud/pump'
import { Route as CloudPluginsRouteImport } from './routes/_cloud/plugins'
import { Route as CloudPairCallbackRouteImport } from './routes/_cloud/pair-callback'
import { Route as CloudDevicesRouteImport } from './routes/_cloud/devices'
import { Route as CloudConnectionsRouteImport } from './routes/_cloud/connections'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated/terminal'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPluginsRouteImport } from './routes/_authenticated/plugins'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedMqttRouteImport } from './routes/_authenticated/mqtt'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as CloudDevicesIndexRouteImport } from './routes/_cloud/devices.index'
import { Route as CloudConnectionsIndexRouteImport } from './routes/_cloud/connections.index'
import { Route as AuthenticatedPluginsIndexRouteImport } from './routes/_authenticated/plugins.index'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as CloudDevicesIdRouteImport } from './routes/_cloud/devices.$id'
import { Route as CloudConnectionsTelegramRouteImport } from './routes/_cloud/connections.telegram'
import { Route as CloudConnectionsMcpRouteImport } from './routes/_cloud/connections.mcp'
import { Route as CloudConnectionsAlexaRouteImport } from './routes/_cloud/connections.alexa'
import { Route as AuthenticatedPluginsIdRouteImport } from './routes/_authenticated/plugins.$id'
import { Route as AuthenticatedContainerIdRouteImport } from './routes/_authenticated/container.$id'
import { Route as ApiPublicVoiceAlexaRouteImport } from './routes/api/public/voice/alexa'
import { Route as ApiPublicOauthTokenRouteImport } from './routes/api/public/oauth/token'
import { Route as ApiPublicOauthAuthorizePostRouteImport } from './routes/api/public/oauth/authorize-post'
import { Route as ApiPublicOauthAuthorizeRouteImport } from './routes/api/public/oauth/authorize'
import { Route as ApiPublicLivePublishRouteImport } from './routes/api/public/live/publish'
import { Route as ApiPublicIngestEventRouteImport } from './routes/api/public/ingest/event'
import { Route as ApiPublicHooksAnomalyScanRouteImport } from './routes/api/public/hooks/anomaly-scan'
import { Route as ApiPublicHooksAggregateEventsRouteImport } from './routes/api/public/hooks/aggregate-events'
import { Route as ApiPublicCloudBridgeStrategyRouteImport } from './routes/api/public/cloud-bridge/strategy'
import { Route as ApiPublicCloudBridgeEventRouteImport } from './routes/api/public/cloud-bridge/event'
import { Route as ApiPublicCloudBridgeClaimRouteImport } from './routes/api/public/cloud-bridge/claim'
import { Route as ApiPublicAgentResultRouteImport } from './routes/api/public/agent/result'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentPollRouteImport } from './routes/api/public/agent/poll'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicTelegramWebhookUserIdRouteImport } from './routes/api/public/telegram/webhook.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/_cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudPumpRoute = CloudPumpRouteImport.update({
  id: '/pump',
  path: '/pump',
  getParentRoute: () => CloudRoute,
} as any)
const CloudPluginsRoute = CloudPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => CloudRoute,
} as any)
const CloudPairCallbackRoute = CloudPairCallbackRouteImport.update({
  id: '/pair-callback',
  path: '/pair-callback',
  getParentRoute: () => CloudRoute,
} as any)
const CloudDevicesRoute = CloudDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => CloudRoute,
} as any)
const CloudConnectionsRoute = CloudConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => CloudRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPluginsRoute = AuthenticatedPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMqttRoute = AuthenticatedMqttRouteImport.update({
  id: '/mqtt',
  path: '/mqtt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CloudDevicesIndexRoute = CloudDevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CloudDevicesRoute,
} as any)
const CloudConnectionsIndexRoute = CloudConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const AuthenticatedPluginsIndexRoute =
  AuthenticatedPluginsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPluginsRoute,
  } as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudDevicesIdRoute = CloudDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CloudDevicesRoute,
} as any)
const CloudConnectionsTelegramRoute =
  CloudConnectionsTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => CloudConnectionsRoute,
  } as any)
const CloudConnectionsMcpRoute = CloudConnectionsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const CloudConnectionsAlexaRoute = CloudConnectionsAlexaRouteImport.update({
  id: '/alexa',
  path: '/alexa',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const AuthenticatedPluginsIdRoute = AuthenticatedPluginsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPluginsRoute,
} as any)
const AuthenticatedContainerIdRoute =
  AuthenticatedContainerIdRouteImport.update({
    id: '/container/$id',
    path: '/container/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicVoiceAlexaRoute = ApiPublicVoiceAlexaRouteImport.update({
  id: '/api/public/voice/alexa',
  path: '/api/public/voice/alexa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthTokenRoute = ApiPublicOauthTokenRouteImport.update({
  id: '/api/public/oauth/token',
  path: '/api/public/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizePostRoute =
  ApiPublicOauthAuthorizePostRouteImport.update({
    id: '/api/public/oauth/authorize-post',
    path: '/api/public/oauth/authorize-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthAuthorizeRoute = ApiPublicOauthAuthorizeRouteImport.update({
  id: '/api/public/oauth/authorize',
  path: '/api/public/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLivePublishRoute = ApiPublicLivePublishRouteImport.update({
  id: '/api/public/live/publish',
  path: '/api/public/live/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestEventRoute = ApiPublicIngestEventRouteImport.update({
  id: '/api/public/ingest/event',
  path: '/api/public/ingest/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAnomalyScanRoute =
  ApiPublicHooksAnomalyScanRouteImport.update({
    id: '/api/public/hooks/anomaly-scan',
    path: '/api/public/hooks/anomaly-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAggregateEventsRoute =
  ApiPublicHooksAggregateEventsRouteImport.update({
    id: '/api/public/hooks/aggregate-events',
    path: '/api/public/hooks/aggregate-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudBridgeStrategyRoute =
  ApiPublicCloudBridgeStrategyRouteImport.update({
    id: '/api/public/cloud-bridge/strategy',
    path: '/api/public/cloud-bridge/strategy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudBridgeEventRoute =
  ApiPublicCloudBridgeEventRouteImport.update({
    id: '/api/public/cloud-bridge/event',
    path: '/api/public/cloud-bridge/event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudBridgeClaimRoute =
  ApiPublicCloudBridgeClaimRouteImport.update({
    id: '/api/public/cloud-bridge/claim',
    path: '/api/public/cloud-bridge/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentResultRoute = ApiPublicAgentResultRouteImport.update({
  id: '/api/public/agent/result',
  path: '/api/public/agent/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPollRoute = ApiPublicAgentPollRouteImport.update({
  id: '/api/public/agent/poll',
  path: '/api/public/agent/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookUserIdRoute =
  ApiPublicTelegramWebhookUserIdRouteImport.update({
    id: '/api/public/telegram/webhook/$userId',
    path: '/api/public/telegram/webhook/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/plugins': typeof CloudPluginsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/connections': typeof CloudConnectionsRouteWithChildren
  '/devices': typeof CloudDevicesRouteWithChildren
  '/pair-callback': typeof CloudPairCallbackRoute
  '/pump': typeof CloudPumpRoute
  '/container/$id': typeof AuthenticatedContainerIdRoute
  '/plugins/$id': typeof AuthenticatedPluginsIdRoute
  '/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/connections/mcp': typeof CloudConnectionsMcpRoute
  '/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/devices/$id': typeof CloudDevicesIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/plugins/': typeof AuthenticatedPluginsIndexRoute
  '/connections/': typeof CloudConnectionsIndexRoute
  '/devices/': typeof CloudDevicesIndexRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/cloud-bridge/claim': typeof ApiPublicCloudBridgeClaimRoute
  '/api/public/cloud-bridge/event': typeof ApiPublicCloudBridgeEventRoute
  '/api/public/cloud-bridge/strategy': typeof ApiPublicCloudBridgeStrategyRoute
  '/api/public/hooks/aggregate-events': typeof ApiPublicHooksAggregateEventsRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/live/publish': typeof ApiPublicLivePublishRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
  '/api/public/telegram/webhook/$userId': typeof ApiPublicTelegramWebhookUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/pair-callback': typeof CloudPairCallbackRoute
  '/plugins': typeof AuthenticatedPluginsIndexRoute
  '/pump': typeof CloudPumpRoute
  '/container/$id': typeof AuthenticatedContainerIdRoute
  '/plugins/$id': typeof AuthenticatedPluginsIdRoute
  '/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/connections/mcp': typeof CloudConnectionsMcpRoute
  '/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/devices/$id': typeof CloudDevicesIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/connections': typeof CloudConnectionsIndexRoute
  '/devices': typeof CloudDevicesIndexRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/cloud-bridge/claim': typeof ApiPublicCloudBridgeClaimRoute
  '/api/public/cloud-bridge/event': typeof ApiPublicCloudBridgeEventRoute
  '/api/public/cloud-bridge/strategy': typeof ApiPublicCloudBridgeStrategyRoute
  '/api/public/hooks/aggregate-events': typeof ApiPublicHooksAggregateEventsRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/live/publish': typeof ApiPublicLivePublishRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
  '/api/public/telegram/webhook/$userId': typeof ApiPublicTelegramWebhookUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_cloud': typeof CloudRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/mqtt': typeof AuthenticatedMqttRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/plugins': typeof AuthenticatedPluginsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_cloud/connections': typeof CloudConnectionsRouteWithChildren
  '/_cloud/devices': typeof CloudDevicesRouteWithChildren
  '/_cloud/pair-callback': typeof CloudPairCallbackRoute
  '/_cloud/plugins': typeof CloudPluginsRoute
  '/_cloud/pump': typeof CloudPumpRoute
  '/_authenticated/container/$id': typeof AuthenticatedContainerIdRoute
  '/_authenticated/plugins/$id': typeof AuthenticatedPluginsIdRoute
  '/_cloud/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/_cloud/connections/mcp': typeof CloudConnectionsMcpRoute
  '/_cloud/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/_cloud/devices/$id': typeof CloudDevicesIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/_authenticated/plugins/': typeof AuthenticatedPluginsIndexRoute
  '/_cloud/connections/': typeof CloudConnectionsIndexRoute
  '/_cloud/devices/': typeof CloudDevicesIndexRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/cloud-bridge/claim': typeof ApiPublicCloudBridgeClaimRoute
  '/api/public/cloud-bridge/event': typeof ApiPublicCloudBridgeEventRoute
  '/api/public/cloud-bridge/strategy': typeof ApiPublicCloudBridgeStrategyRoute
  '/api/public/hooks/aggregate-events': typeof ApiPublicHooksAggregateEventsRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/live/publish': typeof ApiPublicLivePublishRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
  '/api/public/telegram/webhook/$userId': typeof ApiPublicTelegramWebhookUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/integrations'
    | '/mqtt'
    | '/overview'
    | '/plugins'
    | '/settings'
    | '/terminal'
    | '/connections'
    | '/devices'
    | '/pair-callback'
    | '/pump'
    | '/container/$id'
    | '/plugins/$id'
    | '/connections/alexa'
    | '/connections/mcp'
    | '/connections/telegram'
    | '/devices/$id'
    | '/api/public/mcp'
    | '/plugins/'
    | '/connections/'
    | '/devices/'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/cloud-bridge/claim'
    | '/api/public/cloud-bridge/event'
    | '/api/public/cloud-bridge/strategy'
    | '/api/public/hooks/aggregate-events'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/ingest/event'
    | '/api/public/live/publish'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/voice/alexa'
    | '/api/public/telegram/webhook/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/integrations'
    | '/mqtt'
    | '/overview'
    | '/settings'
    | '/terminal'
    | '/pair-callback'
    | '/plugins'
    | '/pump'
    | '/container/$id'
    | '/plugins/$id'
    | '/connections/alexa'
    | '/connections/mcp'
    | '/connections/telegram'
    | '/devices/$id'
    | '/api/public/mcp'
    | '/connections'
    | '/devices'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/cloud-bridge/claim'
    | '/api/public/cloud-bridge/event'
    | '/api/public/cloud-bridge/strategy'
    | '/api/public/hooks/aggregate-events'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/ingest/event'
    | '/api/public/live/publish'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/voice/alexa'
    | '/api/public/telegram/webhook/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_cloud'
    | '/auth'
    | '/login'
    | '/_authenticated/integrations'
    | '/_authenticated/mqtt'
    | '/_authenticated/overview'
    | '/_authenticated/plugins'
    | '/_authenticated/settings'
    | '/_authenticated/terminal'
    | '/_cloud/connections'
    | '/_cloud/devices'
    | '/_cloud/pair-callback'
    | '/_cloud/plugins'
    | '/_cloud/pump'
    | '/_authenticated/container/$id'
    | '/_authenticated/plugins/$id'
    | '/_cloud/connections/alexa'
    | '/_cloud/connections/mcp'
    | '/_cloud/connections/telegram'
    | '/_cloud/devices/$id'
    | '/api/public/mcp'
    | '/_authenticated/plugins/'
    | '/_cloud/connections/'
    | '/_cloud/devices/'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/cloud-bridge/claim'
    | '/api/public/cloud-bridge/event'
    | '/api/public/cloud-bridge/strategy'
    | '/api/public/hooks/aggregate-events'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/ingest/event'
    | '/api/public/live/publish'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/voice/alexa'
    | '/api/public/telegram/webhook/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CloudRoute: typeof CloudRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentPollRoute: typeof ApiPublicAgentPollRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentResultRoute: typeof ApiPublicAgentResultRoute
  ApiPublicCloudBridgeClaimRoute: typeof ApiPublicCloudBridgeClaimRoute
  ApiPublicCloudBridgeEventRoute: typeof ApiPublicCloudBridgeEventRoute
  ApiPublicCloudBridgeStrategyRoute: typeof ApiPublicCloudBridgeStrategyRoute
  ApiPublicHooksAggregateEventsRoute: typeof ApiPublicHooksAggregateEventsRoute
  ApiPublicHooksAnomalyScanRoute: typeof ApiPublicHooksAnomalyScanRoute
  ApiPublicIngestEventRoute: typeof ApiPublicIngestEventRoute
  ApiPublicLivePublishRoute: typeof ApiPublicLivePublishRoute
  ApiPublicOauthAuthorizeRoute: typeof ApiPublicOauthAuthorizeRoute
  ApiPublicOauthAuthorizePostRoute: typeof ApiPublicOauthAuthorizePostRoute
  ApiPublicOauthTokenRoute: typeof ApiPublicOauthTokenRoute
  ApiPublicVoiceAlexaRoute: typeof ApiPublicVoiceAlexaRoute
  ApiPublicTelegramWebhookUserIdRoute: typeof ApiPublicTelegramWebhookUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cloud': {
      id: '/_cloud'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cloud/pump': {
      id: '/_cloud/pump'
      path: '/pump'
      fullPath: '/pump'
      preLoaderRoute: typeof CloudPumpRouteImport
      parentRoute: typeof CloudRoute
    }
    '/_cloud/plugins': {
      id: '/_cloud/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof CloudPluginsRouteImport
      parentRoute: typeof CloudRoute
    }
    '/_cloud/pair-callback': {
      id: '/_cloud/pair-callback'
      path: '/pair-callback'
      fullPath: '/pair-callback'
      preLoaderRoute: typeof CloudPairCallbackRouteImport
      parentRoute: typeof CloudRoute
    }
    '/_cloud/devices': {
      id: '/_cloud/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof CloudDevicesRouteImport
      parentRoute: typeof CloudRoute
    }
    '/_cloud/connections': {
      id: '/_cloud/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof CloudConnectionsRouteImport
      parentRoute: typeof CloudRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plugins': {
      id: '/_authenticated/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AuthenticatedPluginsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mqtt': {
      id: '/_authenticated/mqtt'
      path: '/mqtt'
      fullPath: '/mqtt'
      preLoaderRoute: typeof AuthenticatedMqttRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_cloud/devices/': {
      id: '/_cloud/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof CloudDevicesIndexRouteImport
      parentRoute: typeof CloudDevicesRoute
    }
    '/_cloud/connections/': {
      id: '/_cloud/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof CloudConnectionsIndexRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_authenticated/plugins/': {
      id: '/_authenticated/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AuthenticatedPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedPluginsRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cloud/devices/$id': {
      id: '/_cloud/devices/$id'
      path: '/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof CloudDevicesIdRouteImport
      parentRoute: typeof CloudDevicesRoute
    }
    '/_cloud/connections/telegram': {
      id: '/_cloud/connections/telegram'
      path: '/telegram'
      fullPath: '/connections/telegram'
      preLoaderRoute: typeof CloudConnectionsTelegramRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/mcp': {
      id: '/_cloud/connections/mcp'
      path: '/mcp'
      fullPath: '/connections/mcp'
      preLoaderRoute: typeof CloudConnectionsMcpRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/alexa': {
      id: '/_cloud/connections/alexa'
      path: '/alexa'
      fullPath: '/connections/alexa'
      preLoaderRoute: typeof CloudConnectionsAlexaRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_authenticated/plugins/$id': {
      id: '/_authenticated/plugins/$id'
      path: '/$id'
      fullPath: '/plugins/$id'
      preLoaderRoute: typeof AuthenticatedPluginsIdRouteImport
      parentRoute: typeof AuthenticatedPluginsRoute
    }
    '/_authenticated/container/$id': {
      id: '/_authenticated/container/$id'
      path: '/container/$id'
      fullPath: '/container/$id'
      preLoaderRoute: typeof AuthenticatedContainerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/voice/alexa': {
      id: '/api/public/voice/alexa'
      path: '/api/public/voice/alexa'
      fullPath: '/api/public/voice/alexa'
      preLoaderRoute: typeof ApiPublicVoiceAlexaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/token': {
      id: '/api/public/oauth/token'
      path: '/api/public/oauth/token'
      fullPath: '/api/public/oauth/token'
      preLoaderRoute: typeof ApiPublicOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize-post': {
      id: '/api/public/oauth/authorize-post'
      path: '/api/public/oauth/authorize-post'
      fullPath: '/api/public/oauth/authorize-post'
      preLoaderRoute: typeof ApiPublicOauthAuthorizePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize': {
      id: '/api/public/oauth/authorize'
      path: '/api/public/oauth/authorize'
      fullPath: '/api/public/oauth/authorize'
      preLoaderRoute: typeof ApiPublicOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/publish': {
      id: '/api/public/live/publish'
      path: '/api/public/live/publish'
      fullPath: '/api/public/live/publish'
      preLoaderRoute: typeof ApiPublicLivePublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/event': {
      id: '/api/public/ingest/event'
      path: '/api/public/ingest/event'
      fullPath: '/api/public/ingest/event'
      preLoaderRoute: typeof ApiPublicIngestEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/anomaly-scan': {
      id: '/api/public/hooks/anomaly-scan'
      path: '/api/public/hooks/anomaly-scan'
      fullPath: '/api/public/hooks/anomaly-scan'
      preLoaderRoute: typeof ApiPublicHooksAnomalyScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/aggregate-events': {
      id: '/api/public/hooks/aggregate-events'
      path: '/api/public/hooks/aggregate-events'
      fullPath: '/api/public/hooks/aggregate-events'
      preLoaderRoute: typeof ApiPublicHooksAggregateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud-bridge/strategy': {
      id: '/api/public/cloud-bridge/strategy'
      path: '/api/public/cloud-bridge/strategy'
      fullPath: '/api/public/cloud-bridge/strategy'
      preLoaderRoute: typeof ApiPublicCloudBridgeStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud-bridge/event': {
      id: '/api/public/cloud-bridge/event'
      path: '/api/public/cloud-bridge/event'
      fullPath: '/api/public/cloud-bridge/event'
      preLoaderRoute: typeof ApiPublicCloudBridgeEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloud-bridge/claim': {
      id: '/api/public/cloud-bridge/claim'
      path: '/api/public/cloud-bridge/claim'
      fullPath: '/api/public/cloud-bridge/claim'
      preLoaderRoute: typeof ApiPublicCloudBridgeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/result': {
      id: '/api/public/agent/result'
      path: '/api/public/agent/result'
      fullPath: '/api/public/agent/result'
      preLoaderRoute: typeof ApiPublicAgentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/poll': {
      id: '/api/public/agent/poll'
      path: '/api/public/agent/poll'
      fullPath: '/api/public/agent/poll'
      preLoaderRoute: typeof ApiPublicAgentPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook/$userId': {
      id: '/api/public/telegram/webhook/$userId'
      path: '/api/public/telegram/webhook/$userId'
      fullPath: '/api/public/telegram/webhook/$userId'
      preLoaderRoute: typeof ApiPublicTelegramWebhookUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPluginsRouteChildren {
  AuthenticatedPluginsIdRoute: typeof AuthenticatedPluginsIdRoute
  AuthenticatedPluginsIndexRoute: typeof AuthenticatedPluginsIndexRoute
}

const AuthenticatedPluginsRouteChildren: AuthenticatedPluginsRouteChildren = {
  AuthenticatedPluginsIdRoute: AuthenticatedPluginsIdRoute,
  AuthenticatedPluginsIndexRoute: AuthenticatedPluginsIndexRoute,
}

const AuthenticatedPluginsRouteWithChildren =
  AuthenticatedPluginsRoute._addFileChildren(AuthenticatedPluginsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMqttRoute: typeof AuthenticatedMqttRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPluginsRoute: typeof AuthenticatedPluginsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedContainerIdRoute: typeof AuthenticatedContainerIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMqttRoute: AuthenticatedMqttRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPluginsRoute: AuthenticatedPluginsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
  AuthenticatedContainerIdRoute: AuthenticatedContainerIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CloudConnectionsRouteChildren {
  CloudConnectionsAlexaRoute: typeof CloudConnectionsAlexaRoute
  CloudConnectionsMcpRoute: typeof CloudConnectionsMcpRoute
  CloudConnectionsTelegramRoute: typeof CloudConnectionsTelegramRoute
  CloudConnectionsIndexRoute: typeof CloudConnectionsIndexRoute
}

const CloudConnectionsRouteChildren: CloudConnectionsRouteChildren = {
  CloudConnectionsAlexaRoute: CloudConnectionsAlexaRoute,
  CloudConnectionsMcpRoute: CloudConnectionsMcpRoute,
  CloudConnectionsTelegramRoute: CloudConnectionsTelegramRoute,
  CloudConnectionsIndexRoute: CloudConnectionsIndexRoute,
}

const CloudConnectionsRouteWithChildren =
  CloudConnectionsRoute._addFileChildren(CloudConnectionsRouteChildren)

interface CloudDevicesRouteChildren {
  CloudDevicesIdRoute: typeof CloudDevicesIdRoute
  CloudDevicesIndexRoute: typeof CloudDevicesIndexRoute
}

const CloudDevicesRouteChildren: CloudDevicesRouteChildren = {
  CloudDevicesIdRoute: CloudDevicesIdRoute,
  CloudDevicesIndexRoute: CloudDevicesIndexRoute,
}

const CloudDevicesRouteWithChildren = CloudDevicesRoute._addFileChildren(
  CloudDevicesRouteChildren,
)

interface CloudRouteChildren {
  CloudConnectionsRoute: typeof CloudConnectionsRouteWithChildren
  CloudDevicesRoute: typeof CloudDevicesRouteWithChildren
  CloudPairCallbackRoute: typeof CloudPairCallbackRoute
  CloudPluginsRoute: typeof CloudPluginsRoute
  CloudPumpRoute: typeof CloudPumpRoute
}

const CloudRouteChildren: CloudRouteChildren = {
  CloudConnectionsRoute: CloudConnectionsRouteWithChildren,
  CloudDevicesRoute: CloudDevicesRouteWithChildren,
  CloudPairCallbackRoute: CloudPairCallbackRoute,
  CloudPluginsRoute: CloudPluginsRoute,
  CloudPumpRoute: CloudPumpRoute,
}

const CloudRouteWithChildren = CloudRoute._addFileChildren(CloudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CloudRoute: CloudRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentPollRoute: ApiPublicAgentPollRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentResultRoute: ApiPublicAgentResultRoute,
  ApiPublicCloudBridgeClaimRoute: ApiPublicCloudBridgeClaimRoute,
  ApiPublicCloudBridgeEventRoute: ApiPublicCloudBridgeEventRoute,
  ApiPublicCloudBridgeStrategyRoute: ApiPublicCloudBridgeStrategyRoute,
  ApiPublicHooksAggregateEventsRoute: ApiPublicHooksAggregateEventsRoute,
  ApiPublicHooksAnomalyScanRoute: ApiPublicHooksAnomalyScanRoute,
  ApiPublicIngestEventRoute: ApiPublicIngestEventRoute,
  ApiPublicLivePublishRoute: ApiPublicLivePublishRoute,
  ApiPublicOauthAuthorizeRoute: ApiPublicOauthAuthorizeRoute,
  ApiPublicOauthAuthorizePostRoute: ApiPublicOauthAuthorizePostRoute,
  ApiPublicOauthTokenRoute: ApiPublicOauthTokenRoute,
  ApiPublicVoiceAlexaRoute: ApiPublicVoiceAlexaRoute,
  ApiPublicTelegramWebhookUserIdRoute: ApiPublicTelegramWebhookUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
