/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CloudRouteImport } from './routes/_cloud'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedControlRouteImport } from './routes/_authenticated/control'
import { Route as AuthenticatedDebugRouteImport } from './routes/_authenticated/debug'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedMqttRouteImport } from './routes/_authenticated/mqtt'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated/terminal'
import { Route as AuthenticatedTuningRouteImport } from './routes/_authenticated/tuning'
import { Route as CloudConnectionsRouteImport } from './routes/_cloud/connections'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiLiveStreamRouteImport } from './routes/api/live-stream'
import { Route as CloudConnectionsIndexRouteImport } from './routes/_cloud/connections.index'
import { Route as CloudConnectionsAlexaRouteImport } from './routes/_cloud/connections.alexa'
import { Route as CloudConnectionsAssistantRouteImport } from './routes/_cloud/connections.assistant'
import { Route as CloudConnectionsSetupRouteImport } from './routes/_cloud/connections.setup'
import { Route as CloudConnectionsTelegramRouteImport } from './routes/_cloud/connections.telegram'
import { Route as ApiPublicIngestEventRouteImport } from './routes/api/public/ingest/event'
import { Route as ApiPublicIngestLiveRouteImport } from './routes/api/public/ingest/live'
import { Route as ApiPublicIngestTraceRouteImport } from './routes/api/public/ingest/trace'
import { Route as ApiPublicNoderedAnnounceRouteImport } from './routes/api/public/nodered/announce'
import { Route as ApiPublicNoderedConfigRouteImport } from './routes/api/public/nodered/config'
import { Route as ApiPublicOauthAuthorizeRouteImport } from './routes/api/public/oauth/authorize'
import { Route as ApiPublicOauthAuthorizePostRouteImport } from './routes/api/public/oauth/authorize-post'
import { Route as ApiPublicOauthTokenRouteImport } from './routes/api/public/oauth/token'
import { Route as ApiPublicPiEndpointsRouteImport } from './routes/api/public/pi/endpoints'
import { Route as ApiPublicPiHistoryRouteImport } from './routes/api/public/pi/history'
import { Route as ApiPublicPiStateRouteImport } from './routes/api/public/pi/state'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicVoiceAlexaRouteImport } from './routes/api/public/voice/alexa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/_cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedControlRoute = AuthenticatedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebugRoute = AuthenticatedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMqttRoute = AuthenticatedMqttRouteImport.update({
  id: '/mqtt',
  path: '/mqtt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTuningRoute = AuthenticatedTuningRouteImport.update({
  id: '/tuning',
  path: '/tuning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CloudConnectionsRoute = CloudConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => CloudRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStreamRoute = ApiLiveStreamRouteImport.update({
  id: '/api/live-stream',
  path: '/api/live-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudConnectionsIndexRoute = CloudConnectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const CloudConnectionsAlexaRoute = CloudConnectionsAlexaRouteImport.update({
  id: '/alexa',
  path: '/alexa',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const CloudConnectionsAssistantRoute =
  CloudConnectionsAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => CloudConnectionsRoute,
  } as any)
const CloudConnectionsSetupRoute = CloudConnectionsSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => CloudConnectionsRoute,
} as any)
const CloudConnectionsTelegramRoute =
  CloudConnectionsTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => CloudConnectionsRoute,
  } as any)
const ApiPublicIngestEventRoute = ApiPublicIngestEventRouteImport.update({
  id: '/api/public/ingest/event',
  path: '/api/public/ingest/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLiveRoute = ApiPublicIngestLiveRouteImport.update({
  id: '/api/public/ingest/live',
  path: '/api/public/ingest/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestTraceRoute = ApiPublicIngestTraceRouteImport.update({
  id: '/api/public/ingest/trace',
  path: '/api/public/ingest/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNoderedAnnounceRoute =
  ApiPublicNoderedAnnounceRouteImport.update({
    id: '/api/public/nodered/announce',
    path: '/api/public/nodered/announce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNoderedConfigRoute = ApiPublicNoderedConfigRouteImport.update({
  id: '/api/public/nodered/config',
  path: '/api/public/nodered/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizeRoute = ApiPublicOauthAuthorizeRouteImport.update({
  id: '/api/public/oauth/authorize',
  path: '/api/public/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthAuthorizePostRoute =
  ApiPublicOauthAuthorizePostRouteImport.update({
    id: '/api/public/oauth/authorize-post',
    path: '/api/public/oauth/authorize-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthTokenRoute = ApiPublicOauthTokenRouteImport.update({
  id: '/api/public/oauth/token',
  path: '/api/public/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiEndpointsRoute = ApiPublicPiEndpointsRouteImport.update({
  id: '/api/public/pi/endpoints',
  path: '/api/public/pi/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiHistoryRoute = ApiPublicPiHistoryRouteImport.update({
  id: '/api/public/pi/history',
  path: '/api/public/pi/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiStateRoute = ApiPublicPiStateRouteImport.update({
  id: '/api/public/pi/state',
  path: '/api/public/pi/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceAlexaRoute = ApiPublicVoiceAlexaRouteImport.update({
  id: '/api/public/voice/alexa',
  path: '/api/public/voice/alexa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/control': typeof AuthenticatedControlRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/tuning': typeof AuthenticatedTuningRoute
  '/connections': typeof CloudConnectionsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/connections/assistant': typeof CloudConnectionsAssistantRoute
  '/connections/setup': typeof CloudConnectionsSetupRoute
  '/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/connections/': typeof CloudConnectionsIndexRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/ingest/live': typeof ApiPublicIngestLiveRoute
  '/api/public/ingest/trace': typeof ApiPublicIngestTraceRoute
  '/api/public/nodered/announce': typeof ApiPublicNoderedAnnounceRoute
  '/api/public/nodered/config': typeof ApiPublicNoderedConfigRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/pi/endpoints': typeof ApiPublicPiEndpointsRoute
  '/api/public/pi/history': typeof ApiPublicPiHistoryRoute
  '/api/public/pi/state': typeof ApiPublicPiStateRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/control': typeof AuthenticatedControlRoute
  '/debug': typeof AuthenticatedDebugRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/mqtt': typeof AuthenticatedMqttRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/tuning': typeof AuthenticatedTuningRoute
  '/api/chat': typeof ApiChatRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/connections/assistant': typeof CloudConnectionsAssistantRoute
  '/connections/setup': typeof CloudConnectionsSetupRoute
  '/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/connections': typeof CloudConnectionsIndexRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/ingest/live': typeof ApiPublicIngestLiveRoute
  '/api/public/ingest/trace': typeof ApiPublicIngestTraceRoute
  '/api/public/nodered/announce': typeof ApiPublicNoderedAnnounceRoute
  '/api/public/nodered/config': typeof ApiPublicNoderedConfigRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/pi/endpoints': typeof ApiPublicPiEndpointsRoute
  '/api/public/pi/history': typeof ApiPublicPiHistoryRoute
  '/api/public/pi/state': typeof ApiPublicPiStateRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_cloud': typeof CloudRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/_authenticated/control': typeof AuthenticatedControlRoute
  '/_authenticated/debug': typeof AuthenticatedDebugRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/mqtt': typeof AuthenticatedMqttRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/tuning': typeof AuthenticatedTuningRoute
  '/_cloud/connections': typeof CloudConnectionsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/_cloud/connections/alexa': typeof CloudConnectionsAlexaRoute
  '/_cloud/connections/assistant': typeof CloudConnectionsAssistantRoute
  '/_cloud/connections/setup': typeof CloudConnectionsSetupRoute
  '/_cloud/connections/telegram': typeof CloudConnectionsTelegramRoute
  '/_cloud/connections/': typeof CloudConnectionsIndexRoute
  '/api/public/ingest/event': typeof ApiPublicIngestEventRoute
  '/api/public/ingest/live': typeof ApiPublicIngestLiveRoute
  '/api/public/ingest/trace': typeof ApiPublicIngestTraceRoute
  '/api/public/nodered/announce': typeof ApiPublicNoderedAnnounceRoute
  '/api/public/nodered/config': typeof ApiPublicNoderedConfigRoute
  '/api/public/oauth/authorize': typeof ApiPublicOauthAuthorizeRoute
  '/api/public/oauth/authorize-post': typeof ApiPublicOauthAuthorizePostRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/pi/endpoints': typeof ApiPublicPiEndpointsRoute
  '/api/public/pi/history': typeof ApiPublicPiHistoryRoute
  '/api/public/pi/state': typeof ApiPublicPiStateRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/voice/alexa': typeof ApiPublicVoiceAlexaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/control'
    | '/debug'
    | '/integrations'
    | '/mqtt'
    | '/overview'
    | '/settings'
    | '/terminal'
    | '/tuning'
    | '/connections'
    | '/api/chat'
    | '/api/live-stream'
    | '/connections/alexa'
    | '/connections/assistant'
    | '/connections/setup'
    | '/connections/telegram'
    | '/connections/'
    | '/api/public/ingest/event'
    | '/api/public/ingest/live'
    | '/api/public/ingest/trace'
    | '/api/public/nodered/announce'
    | '/api/public/nodered/config'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/pi/endpoints'
    | '/api/public/pi/history'
    | '/api/public/pi/state'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/alexa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/control'
    | '/debug'
    | '/integrations'
    | '/mqtt'
    | '/overview'
    | '/settings'
    | '/terminal'
    | '/tuning'
    | '/api/chat'
    | '/api/live-stream'
    | '/connections/alexa'
    | '/connections/assistant'
    | '/connections/setup'
    | '/connections/telegram'
    | '/connections'
    | '/api/public/ingest/event'
    | '/api/public/ingest/live'
    | '/api/public/ingest/trace'
    | '/api/public/nodered/announce'
    | '/api/public/nodered/config'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/pi/endpoints'
    | '/api/public/pi/history'
    | '/api/public/pi/state'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/alexa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_cloud'
    | '/auth'
    | '/login'
    | '/_authenticated/control'
    | '/_authenticated/debug'
    | '/_authenticated/integrations'
    | '/_authenticated/mqtt'
    | '/_authenticated/overview'
    | '/_authenticated/settings'
    | '/_authenticated/terminal'
    | '/_authenticated/tuning'
    | '/_cloud/connections'
    | '/api/chat'
    | '/api/live-stream'
    | '/_cloud/connections/alexa'
    | '/_cloud/connections/assistant'
    | '/_cloud/connections/setup'
    | '/_cloud/connections/telegram'
    | '/_cloud/connections/'
    | '/api/public/ingest/event'
    | '/api/public/ingest/live'
    | '/api/public/ingest/trace'
    | '/api/public/nodered/announce'
    | '/api/public/nodered/config'
    | '/api/public/oauth/authorize'
    | '/api/public/oauth/authorize-post'
    | '/api/public/oauth/token'
    | '/api/public/pi/endpoints'
    | '/api/public/pi/history'
    | '/api/public/pi/state'
    | '/api/public/telegram/webhook'
    | '/api/public/voice/alexa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CloudRoute: typeof CloudRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLiveStreamRoute: typeof ApiLiveStreamRoute
  ApiPublicIngestEventRoute: typeof ApiPublicIngestEventRoute
  ApiPublicIngestLiveRoute: typeof ApiPublicIngestLiveRoute
  ApiPublicIngestTraceRoute: typeof ApiPublicIngestTraceRoute
  ApiPublicNoderedAnnounceRoute: typeof ApiPublicNoderedAnnounceRoute
  ApiPublicNoderedConfigRoute: typeof ApiPublicNoderedConfigRoute
  ApiPublicOauthAuthorizeRoute: typeof ApiPublicOauthAuthorizeRoute
  ApiPublicOauthAuthorizePostRoute: typeof ApiPublicOauthAuthorizePostRoute
  ApiPublicOauthTokenRoute: typeof ApiPublicOauthTokenRoute
  ApiPublicPiEndpointsRoute: typeof ApiPublicPiEndpointsRoute
  ApiPublicPiHistoryRoute: typeof ApiPublicPiHistoryRoute
  ApiPublicPiStateRoute: typeof ApiPublicPiStateRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicVoiceAlexaRoute: typeof ApiPublicVoiceAlexaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cloud': {
      id: '/_cloud'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/control': {
      id: '/_authenticated/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AuthenticatedControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debug': {
      id: '/_authenticated/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof AuthenticatedDebugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mqtt': {
      id: '/_authenticated/mqtt'
      path: '/mqtt'
      fullPath: '/mqtt'
      preLoaderRoute: typeof AuthenticatedMqttRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tuning': {
      id: '/_authenticated/tuning'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof AuthenticatedTuningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_cloud/connections': {
      id: '/_cloud/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof CloudConnectionsRouteImport
      parentRoute: typeof CloudRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-stream': {
      id: '/api/live-stream'
      path: '/api/live-stream'
      fullPath: '/api/live-stream'
      preLoaderRoute: typeof ApiLiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cloud/connections/': {
      id: '/_cloud/connections/'
      path: '/'
      fullPath: '/connections/'
      preLoaderRoute: typeof CloudConnectionsIndexRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/alexa': {
      id: '/_cloud/connections/alexa'
      path: '/alexa'
      fullPath: '/connections/alexa'
      preLoaderRoute: typeof CloudConnectionsAlexaRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/assistant': {
      id: '/_cloud/connections/assistant'
      path: '/assistant'
      fullPath: '/connections/assistant'
      preLoaderRoute: typeof CloudConnectionsAssistantRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/setup': {
      id: '/_cloud/connections/setup'
      path: '/setup'
      fullPath: '/connections/setup'
      preLoaderRoute: typeof CloudConnectionsSetupRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/_cloud/connections/telegram': {
      id: '/_cloud/connections/telegram'
      path: '/telegram'
      fullPath: '/connections/telegram'
      preLoaderRoute: typeof CloudConnectionsTelegramRouteImport
      parentRoute: typeof CloudConnectionsRoute
    }
    '/api/public/ingest/event': {
      id: '/api/public/ingest/event'
      path: '/api/public/ingest/event'
      fullPath: '/api/public/ingest/event'
      preLoaderRoute: typeof ApiPublicIngestEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/live': {
      id: '/api/public/ingest/live'
      path: '/api/public/ingest/live'
      fullPath: '/api/public/ingest/live'
      preLoaderRoute: typeof ApiPublicIngestLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/trace': {
      id: '/api/public/ingest/trace'
      path: '/api/public/ingest/trace'
      fullPath: '/api/public/ingest/trace'
      preLoaderRoute: typeof ApiPublicIngestTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nodered/announce': {
      id: '/api/public/nodered/announce'
      path: '/api/public/nodered/announce'
      fullPath: '/api/public/nodered/announce'
      preLoaderRoute: typeof ApiPublicNoderedAnnounceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nodered/config': {
      id: '/api/public/nodered/config'
      path: '/api/public/nodered/config'
      fullPath: '/api/public/nodered/config'
      preLoaderRoute: typeof ApiPublicNoderedConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize': {
      id: '/api/public/oauth/authorize'
      path: '/api/public/oauth/authorize'
      fullPath: '/api/public/oauth/authorize'
      preLoaderRoute: typeof ApiPublicOauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/authorize-post': {
      id: '/api/public/oauth/authorize-post'
      path: '/api/public/oauth/authorize-post'
      fullPath: '/api/public/oauth/authorize-post'
      preLoaderRoute: typeof ApiPublicOauthAuthorizePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/token': {
      id: '/api/public/oauth/token'
      path: '/api/public/oauth/token'
      fullPath: '/api/public/oauth/token'
      preLoaderRoute: typeof ApiPublicOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/endpoints': {
      id: '/api/public/pi/endpoints'
      path: '/api/public/pi/endpoints'
      fullPath: '/api/public/pi/endpoints'
      preLoaderRoute: typeof ApiPublicPiEndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/history': {
      id: '/api/public/pi/history'
      path: '/api/public/pi/history'
      fullPath: '/api/public/pi/history'
      preLoaderRoute: typeof ApiPublicPiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/state': {
      id: '/api/public/pi/state'
      path: '/api/public/pi/state'
      fullPath: '/api/public/pi/state'
      preLoaderRoute: typeof ApiPublicPiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice/alexa': {
      id: '/api/public/voice/alexa'
      path: '/api/public/voice/alexa'
      fullPath: '/api/public/voice/alexa'
      preLoaderRoute: typeof ApiPublicVoiceAlexaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedControlRoute: typeof AuthenticatedControlRoute
  AuthenticatedDebugRoute: typeof AuthenticatedDebugRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMqttRoute: typeof AuthenticatedMqttRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedTuningRoute: typeof AuthenticatedTuningRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedControlRoute: AuthenticatedControlRoute,
  AuthenticatedDebugRoute: AuthenticatedDebugRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMqttRoute: AuthenticatedMqttRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
  AuthenticatedTuningRoute: AuthenticatedTuningRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CloudConnectionsRouteChildren {
  CloudConnectionsAlexaRoute: typeof CloudConnectionsAlexaRoute
  CloudConnectionsAssistantRoute: typeof CloudConnectionsAssistantRoute
  CloudConnectionsSetupRoute: typeof CloudConnectionsSetupRoute
  CloudConnectionsTelegramRoute: typeof CloudConnectionsTelegramRoute
  CloudConnectionsIndexRoute: typeof CloudConnectionsIndexRoute
}

const CloudConnectionsRouteChildren: CloudConnectionsRouteChildren = {
  CloudConnectionsAlexaRoute: CloudConnectionsAlexaRoute,
  CloudConnectionsAssistantRoute: CloudConnectionsAssistantRoute,
  CloudConnectionsSetupRoute: CloudConnectionsSetupRoute,
  CloudConnectionsTelegramRoute: CloudConnectionsTelegramRoute,
  CloudConnectionsIndexRoute: CloudConnectionsIndexRoute,
}

const CloudConnectionsRouteWithChildren =
  CloudConnectionsRoute._addFileChildren(CloudConnectionsRouteChildren)

interface CloudRouteChildren {
  CloudConnectionsRoute: typeof CloudConnectionsRouteWithChildren
}

const CloudRouteChildren: CloudRouteChildren = {
  CloudConnectionsRoute: CloudConnectionsRouteWithChildren,
}

const CloudRouteWithChildren = CloudRoute._addFileChildren(CloudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CloudRoute: CloudRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLiveStreamRoute: ApiLiveStreamRoute,
  ApiPublicIngestEventRoute: ApiPublicIngestEventRoute,
  ApiPublicIngestLiveRoute: ApiPublicIngestLiveRoute,
  ApiPublicIngestTraceRoute: ApiPublicIngestTraceRoute,
  ApiPublicNoderedAnnounceRoute: ApiPublicNoderedAnnounceRoute,
  ApiPublicNoderedConfigRoute: ApiPublicNoderedConfigRoute,
  ApiPublicOauthAuthorizeRoute: ApiPublicOauthAuthorizeRoute,
  ApiPublicOauthAuthorizePostRoute: ApiPublicOauthAuthorizePostRoute,
  ApiPublicOauthTokenRoute: ApiPublicOauthTokenRoute,
  ApiPublicPiEndpointsRoute: ApiPublicPiEndpointsRoute,
  ApiPublicPiHistoryRoute: ApiPublicPiHistoryRoute,
  ApiPublicPiStateRoute: ApiPublicPiStateRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicVoiceAlexaRoute: ApiPublicVoiceAlexaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
